use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

target 'NetWorkAuthorizationTool_Example' do
  pod 'NetWorkAuthorizationTool', :path => '../'

  target 'NetWorkAuthorizationTool_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
